services:
  - type: web
    name: sentiment-analysis
    env: python
    buildCommand: pip install -r requirements.txt && python download_assets.py
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: MODEL_PATH
        value: c1_lstm_model_acc_0.865.h5
      - key: PORT
        value: 10000
      - key: TF_CPP_MIN_LOG_LEVEL
        value: 2
    disk:
      name: assets
      mountPath: /app/assets
      sizeGB: 1